name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  spec:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '1.9.3-p551'
          - '2.0.0-p648'
          - '2.1.9'
          - '2.2.10'
          - '2.3.8'
          - '2.4.10'
          - '2.5.9'
          - '2.6.10'
          - '2.7.8'
          - '3.0.7'
          - '3.1.7'
          - '3.2.9'
          - '3.3.10'
          - '3.4.8'
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@d354de180d0c9e813cfddfcbdc079945d4be589b # v1.275.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake build
      - run: bundle exec rake spec
